/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OpenQASM3AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/openqasm/parser/antlr/internal/InternalOpenQASM3.tokens");
	}
}
