/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.openqasm.parser.antlr.internal.InternalOpenQASM3Parser;
import org.xtext.openqasm.services.OpenQASM3GrammarAccess;

public class OpenQASM3Parser extends AbstractAntlrParser {

	@Inject
	private OpenQASM3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOpenQASM3Parser createParser(XtextTokenStream stream) {
		return new InternalOpenQASM3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public OpenQASM3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OpenQASM3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
