/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class OpenQASM3UiModule extends AbstractOpenQASM3UiModule {

	public OpenQASM3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
