/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.Expression#getExprs <em>Exprs</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.Expression#getLtrs <em>Ltrs</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.Expression#getUnExpressions <em>Un Expressions</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.Expression#getMultExpressions <em>Mult Expressions</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.Expression#getE <em>E</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression()
 * @model
 * @generated
 */
public interface Expression extends IndexOperator
{
  /**
   * Returns the value of the '<em><b>Exprs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprs</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression_Exprs()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getExprs();

  /**
   * Returns the value of the '<em><b>Ltrs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.Literal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ltrs</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression_Ltrs()
   * @model containment="true"
   * @generated
   */
  EList<Literal> getLtrs();

  /**
   * Returns the value of the '<em><b>Un Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.UnaryExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Un Expressions</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression_UnExpressions()
   * @model containment="true"
   * @generated
   */
  EList<UnaryExpression> getUnExpressions();

  /**
   * Returns the value of the '<em><b>Mult Expressions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.MultiplicativeExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mult Expressions</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression_MultExpressions()
   * @model containment="true"
   * @generated
   */
  EList<MultiplicativeExpression> getMultExpressions();

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpression_E()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getE();

} // Expression
