/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.ExpressionList#getE1 <em>E1</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.ExpressionList#getE2 <em>E2</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpressionList()
 * @model
 * @generated
 */
public interface ExpressionList extends EObject
{
  /**
   * Returns the value of the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E1</em>' containment reference.
   * @see #setE1(Expression)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpressionList_E1()
   * @model containment="true"
   * @generated
   */
  Expression getE1();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.ExpressionList#getE1 <em>E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E1</em>' containment reference.
   * @see #getE1()
   * @generated
   */
  void setE1(Expression value);

  /**
   * Returns the value of the '<em><b>E2</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E2</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getExpressionList_E2()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getE2();

} // ExpressionList
