/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.IfStatement#getCondition <em>Condition</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.IfStatement#getIf_body <em>If body</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(Expression)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIfStatement_Condition()
   * @model containment="true"
   * @generated
   */
  Expression getCondition();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.IfStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(Expression value);

  /**
   * Returns the value of the '<em><b>If body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>If body</em>' containment reference.
   * @see #setIf_body(statementOrScope)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIfStatement_If_body()
   * @model containment="true"
   * @generated
   */
  statementOrScope getIf_body();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.IfStatement#getIf_body <em>If body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If body</em>' containment reference.
   * @see #getIf_body()
   * @generated
   */
  void setIf_body(statementOrScope value);

} // IfStatement
