/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Include Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.IncludeStatement#getLibName <em>Lib Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIncludeStatement()
 * @model
 * @generated
 */
public interface IncludeStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Lib Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lib Name</em>' attribute.
   * @see #setLibName(String)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIncludeStatement_LibName()
   * @model
   * @generated
   */
  String getLibName();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.IncludeStatement#getLibName <em>Lib Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lib Name</em>' attribute.
   * @see #getLibName()
   * @generated
   */
  void setLibName(String value);

} // IncludeStatement
