/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Indexed Identifier</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.IndexedIdentifier#getGateName <em>Gate Name</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.IndexedIdentifier#getIo <em>Io</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIndexedIdentifier()
 * @model
 * @generated
 */
public interface IndexedIdentifier extends GateOperand
{
  /**
   * Returns the value of the '<em><b>Gate Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gate Name</em>' attribute.
   * @see #setGateName(String)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIndexedIdentifier_GateName()
   * @model
   * @generated
   */
  String getGateName();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.IndexedIdentifier#getGateName <em>Gate Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gate Name</em>' attribute.
   * @see #getGateName()
   * @generated
   */
  void setGateName(String value);

  /**
   * Returns the value of the '<em><b>Io</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.IndexOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Io</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIndexedIdentifier_Io()
   * @model containment="true"
   * @generated
   */
  EList<IndexOperator> getIo();

} // IndexedIdentifier
