/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Index Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getIndexOperator()
 * @model
 * @generated
 */
public interface IndexOperator extends EObject
{
} // IndexOperator
