/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Multiplicative Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.MultiplicativeExpression#getL1 <em>L1</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getMultiplicativeExpression()
 * @model
 * @generated
 */
public interface MultiplicativeExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>L1</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.openqasm.openQASM3.Literal}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>L1</em>' containment reference list.
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getMultiplicativeExpression_L1()
   * @model containment="true"
   * @generated
   */
  EList<Literal> getL1();

} // MultiplicativeExpression
