/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>quantum Declaration Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getquantumDeclarationStatement()
 * @model
 * @generated
 */
public interface quantumDeclarationStatement extends Statement
{
} // quantumDeclarationStatement
