/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Qubit Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.QubitType#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.openqasm.openQASM3.QubitType#getD <em>D</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getQubitType()
 * @model
 * @generated
 */
public interface QubitType extends quantumDeclarationStatement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getQubitType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.QubitType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>D</em>' containment reference.
   * @see #setD(Designator)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getQubitType_D()
   * @model containment="true"
   * @generated
   */
  Designator getD();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.QubitType#getD <em>D</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>D</em>' containment reference.
   * @see #getD()
   * @generated
   */
  void setD(Designator value);

} // QubitType
