/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Version</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.openqasm.openQASM3.Version#getVersionNumber <em>Version Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getVersion()
 * @model
 * @generated
 */
public interface Version extends EObject
{
  /**
   * Returns the value of the '<em><b>Version Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version Number</em>' attribute.
   * @see #setVersionNumber(String)
   * @see org.xtext.openqasm.openQASM3.OpenQASM3Package#getVersion_VersionNumber()
   * @model
   * @generated
   */
  String getVersionNumber();

  /**
   * Sets the value of the '{@link org.xtext.openqasm.openQASM3.Version#getVersionNumber <em>Version Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version Number</em>' attribute.
   * @see #getVersionNumber()
   * @generated
   */
  void setVersionNumber(String value);

} // Version
