/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOpenQASM3Validator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.openqasm.openQASM3.OpenQASM3Package.eINSTANCE);
		return result;
	}
}
