/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.openqasm.openQASM3.OpenQASM3Package;
import org.xtext.openqasm.openQASM3.quantumDeclarationStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>quantum Declaration Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class quantumDeclarationStatementImpl extends StatementImpl implements quantumDeclarationStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected quantumDeclarationStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenQASM3Package.Literals.QUANTUM_DECLARATION_STATEMENT;
  }

} //quantumDeclarationStatementImpl
