/**
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.openQASM3.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.openqasm.openQASM3.OpenQASM3Package;
import org.xtext.openqasm.openQASM3.statementOrScope;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>statement Or Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class statementOrScopeImpl extends MinimalEObjectImpl.Container implements statementOrScope
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected statementOrScopeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenQASM3Package.Literals.STATEMENT_OR_SCOPE;
  }

} //statementOrScopeImpl
