/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import qasmDraw.ui.internal.QasmDrawActivator;

public class OpenQASM3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return QasmDrawActivator.getInstance().getInjector("org.xtext.openqasm.OpenQASM3");
	}

}
