/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import qasmDraw.ui.internal.QasmDrawActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OpenQASM3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(QasmDrawActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		QasmDrawActivator activator = QasmDrawActivator.getInstance();
		return activator != null ? activator.getInjector(QasmDrawActivator.ORG_XTEXT_OPENQASM_OPENQASM3) : null;
	}

}
