/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OpenQASM3StandaloneSetup extends OpenQASM3StandaloneSetupGenerated {

	public static void doSetup() {
		new OpenQASM3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
