/*
 * generated by Xtext 2.30.0
 */
package org.xtext.openqasm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOpenQASM3ScopeProvider extends DelegatingScopeProvider {
}
